# Generated by Django 5.2.5 on 2025-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=32, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='long',
            field=models.DecimalField(decimal_places=6, default=34, max_digits=9),
            preserve_default=False,
        ),
    ]
