# Generated by Django 5.2.5 on 2025-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Worker'), (3, 'Client')], default=1),
            preserve_default=False,
        ),
    ]
