# Generated by Django 5.2.5 on 2025-08-26 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=32, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='long',
            field=models.DecimalField(decimal_places=6, default=34, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'Done')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=342, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Done'), (4, 'CANCELED')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='worker_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
