# Generated by Django 5.2.5 on 2025-08-26 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_lat_order_long_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'Done')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='worker_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
